SYMBOL = "XAUUSDm"
TIMEFRAME_H4 = "H4"
TIMEFRAME_H1 = "M30"

EMA_PERIOD = 100
RSI_PERIOD = 14
RSI_OVERSOLD_LEVEL = 30

SWING_LOOKBACK_CANDLES = 10

TELEGRAM_BOT_TOKEN = None
TELEGRAM_CHAT_ID = None

CHECK_INTERVAL_SECONDS = 3600